## Combine SFO NOAA/Flight/FAA Data

This notebook loads the three major preprocessed datasets for inspection and merging.

### Load CSV datasets

In [1]:
from pathlib import Path

import gdown
import pandas as pd

DRIVE_FOLDER_URL = "https://drive.google.com/drive/folders/1SLMsPvHSMyiL9l5-lXEOh9OtPv11pVAU?usp=drive_link"

ROOT_DIR = Path.cwd().parents[0]

NOTEBOOK_DIR = ROOT_DIR / "Merged_EDA"
RAW_DATA_DIR = NOTEBOOK_DIR / "raw_data"
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)

### Download the datasets

In [2]:
downloaded_paths = gdown.download_folder(
    url=DRIVE_FOLDER_URL,
    output=str(RAW_DATA_DIR),
    quiet=False,
    use_cookies=False,
    resume=True,  # Skip files that are already in raw_data
)

Retrieving folder contents

Processing file 1B88PbmqDrsy-3dgFrhwQGAGHesnuw94L FAA_dataset.csv
Processing file 1ULQDbtOQlQiOlDcI0j_z6Izhf0j1X7Nr SFO_Departures_dataset.csv
Processing file 1cT9dmnSz4grCOPrYSRIY_pOJ_gPs7TGv SFO_NOAA_dataset.csv

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Skipping already downloaded file c:\Users\smeri\OneDrive\Desktop\MIDS Coursework\207-Summer26-FinalProject-MLModel\Merged_EDA\raw_data\FAA_dataset.csv
Skipping already downloaded file c:\Users\smeri\OneDrive\Desktop\MIDS Coursework\207-Summer26-FinalProject-MLModel\Merged_EDA\raw_data\SFO_Departures_dataset.csv
Skipping already downloaded file c:\Users\smeri\OneDrive\Desktop\MIDS Coursework\207-Summer26-FinalProject-MLModel\Merged_EDA\raw_data\SFO_NOAA_dataset.csv
Download completed

### Preview each dataset

In [3]:
csv_files = sorted(RAW_DATA_DIR.rglob("*.csv"))

datasets = {}

for csv_path in csv_files:
    dataset_name = csv_path.stem
    datasets[dataset_name] = pd.read_csv(csv_path, low_memory=False)

    print(f"{dataset_name}: {datasets[dataset_name].shape}")
    display(datasets[dataset_name].head())

FAA_dataset: (313930, 17)

,N-NUMBER,YEAR MFR,TYPE AIRCRAFT,TYPE ENGINE,MFR MDL CODE,ENG MFR MDL,CODE,MFR,MODEL,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,CODE_ENG,MFR_ENG,MODEL_ENG,THRUST
0,100,1940,4,1,7100510,17003.0,7100510,PIPER,J3C-65,1,2,CLASS 1,67,17003.0,CONT MOTOR,A&C65 SERIES,0.0
1,10000,,4,1,2130004,NaN,2130004,CIRRUS DESIGN CORP,SR22T,1,5,CLASS 1,0,NaN,NaN,NaN,NaN
2,10001,1928,4,1,9601202,67007.0,9601202,WACO,ASO,1,3,CLASS 1,79,67007.0,WRIGHT,WWJ SERIES,0.0
3,10004,,4,2,2072738,NaN,2072738,CESSNA,T182T,1,4,CLASS 1,0,NaN,NaN,NaN,NaN
4,10006,1955,4,1,1152020,17026.0,1152020,BEECH,D-45 (T-34B),1,4,CLASS 1,0,17026.0,CONT MOTOR,O-470 SERIES,0.0

SFO_Departures_dataset: (444160, 35)

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,month,month_name,day_of_week,is_weekend,sched_dep_hour,dep_time_of_day,is_holiday,days_until_holiday,days_from_holiday,mod_tail_number
0,AA,01/01/2022,16.0,N110AN,JFK,11:46,11:35,343.0,328.0,-11.0,...,1.0,Jan,5.0,1,11.0,morning,1,0.0,0.0,110AN
1,AA,01/01/2022,234.0,N112AN,JFK,07:00,06:54,329.0,328.0,-6.0,...,1.0,Jan,5.0,1,7.0,morning,1,0.0,0.0,112AN
2,AA,01/01/2022,276.0,N109NN,JFK,22:59,22:51,333.0,329.0,-8.0,...,1.0,Jan,5.0,1,22.0,evening/night,1,0.0,0.0,109NN
3,AA,01/01/2022,369.0,N341SV,MIA,07:47,07:43,330.0,303.0,-4.0,...,1.0,Jan,5.0,1,7.0,morning,1,0.0,0.0,341SV
4,AA,01/01/2022,1175.0,N992AN,DFW,17:21,17:31,208.0,195.0,10.0,...,1.0,Jan,5.0,1,17.0,afternoon,1,0.0,0.0,992AN

SFO_NOAA_dataset: (38732, 23)

,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,ELEVATION,temperature,...,wind_speed,wind_direction,sea_level_pressure,station_level_pressure,wet_bulb_temperature,ceiling_height,altimeter,sky_condition_baseht,sky_cover_summation_baseht_1,precipitation
0,2022-01-01 00:56:00,2022,1,1,0,56,37.6197,-122.3656,3.0,10.6,...,7.2,300.0,1012.8,1012.3,7.9,22000.0,1012.9,610.0,610.0,0.0
1,2022-01-01 01:56:00,2022,1,1,1,56,37.6197,-122.3656,3.0,10.0,...,5.1,300.0,1013.3,1012.6,7.4,22000.0,1013.2,579.0,579.0,0.0
2,2022-01-01 02:56:00,2022,1,1,2,56,37.6197,-122.3656,3.0,9.4,...,5.1,290.0,1014.0,1013.6,7.1,22000.0,1014.2,NaN,NaN,0.0
3,2022-01-01 03:56:00,2022,1,1,3,56,37.6197,-122.3656,3.0,9.4,...,5.1,310.0,1014.6,1014.0,7.3,22000.0,1014.6,914.0,914.0,0.0
4,2022-01-01 04:56:00,2022,1,1,4,56,37.6197,-122.3656,3.0,8.9,...,2.6,330.0,1015.5,1015.0,7.1,22000.0,1015.6,NaN,NaN,0.0

### Load Datasets

In [4]:
faa_df = pd.read_csv("raw_data/FAA_dataset.csv")
departures_df = pd.read_csv("raw_data/SFO_Departures_dataset.csv")
noaa_df = pd.read_csv("raw_data/SFO_NOAA_dataset.csv")

### Merge Departures/FAA on Tail Number

In [5]:
# Normalizing tail numbers in both datasets to create a common key for merging
departures_df["tail_key"] = (
    departures_df["mod_tail_number"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"^N", "", regex=True)
)

faa_df["tail_key"] = (
    faa_df["N-NUMBER"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"^N", "", regex=True)
)

departures_faa_df = departures_df.merge(
    faa_df,
    on="tail_key",
    how="left",
    validate="many_to_one",
    indicator=True,
)

print(f"departures_faa_df shape: {departures_faa_df.shape}")
display(departures_faa_df.head())

departures_faa_df shape: (444160, 54)

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,MODEL,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,CODE_ENG,MFR_ENG,MODEL_ENG,THRUST,_merge
0,AA,01/01/2022,16.0,N110AN,JFK,11:46,11:35,343.0,328.0,-11.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
1,AA,01/01/2022,234.0,N112AN,JFK,07:00,06:54,329.0,328.0,-6.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
2,AA,01/01/2022,276.0,N109NN,JFK,22:59,22:51,333.0,329.0,-8.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
3,AA,01/01/2022,369.0,N341SV,MIA,07:47,07:43,330.0,303.0,-4.0,...,737-8,2.0,175.0,CLASS 3,0.0,13134.0,CFM INTL,LEAP-1B25,26786.0,both
4,AA,01/01/2022,1175.0,N992AN,DFW,17:21,17:31,208.0,195.0,10.0,...,737-823,2.0,162.0,CLASS 3,0.0,13074.0,CFM INTL,CFM56-7B24/3,22800.0,both

### Identify Mismatches

In [6]:
print(departures_faa_df["_merge"].value_counts())

match_rate = departures_faa_df["_merge"].eq("both").mean()
print(f"FAA match rate: {match_rate:.2%}")

mismatches_df = departures_faa_df[
    departures_faa_df["_merge"] != "both"
]
display(mismatches_df)

_merge
both          423890
left_only      20270
right_only         0
Name: count, dtype: int64
FAA match rate: 95.44%

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,MODEL,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,CODE_ENG,MFR_ENG,MODEL_ENG,THRUST,_merge
4157,AA,02/03/2022,2891.0,N823AW,LAX,08:01,07:53,96.0,62.0,-8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17345,AA,05/10/2022,2016.0,N823AW,PHX,12:38,12:38,116.0,110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
28432,AA,08/10/2022,2018.0,N823AW,PHX,09:15,09:06,120.0,111.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43594,AA,12/16/2024,637.0,N823AW,LAX,11:47,11:43,87.0,109.0,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43595,AA,12/16/2024,677.0,N823AW,LAX,16:15,16:06,88.0,79.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444109,WN,12/31/2023,2218.0,N492WN,LAS,10:15,10:30,90.0,80.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444124,WN,12/31/2024,1073.0,N7722B,DEN,07:55,07:58,145.0,127.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444129,WN,12/31/2024,2290.0,N230WN,DEN,13:20,14:02,150.0,129.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444133,WN,12/31/2024,2712.0,N8627B,DEN,09:55,09:52,140.0,124.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444159,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [7]:
display(departures_faa_df[departures_faa_df["_merge"] != "both"])

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,MODEL,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,CODE_ENG,MFR_ENG,MODEL_ENG,THRUST,_merge
4157,AA,02/03/2022,2891.0,N823AW,LAX,08:01,07:53,96.0,62.0,-8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17345,AA,05/10/2022,2016.0,N823AW,PHX,12:38,12:38,116.0,110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
28432,AA,08/10/2022,2018.0,N823AW,PHX,09:15,09:06,120.0,111.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43594,AA,12/16/2024,637.0,N823AW,LAX,11:47,11:43,87.0,109.0,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43595,AA,12/16/2024,677.0,N823AW,LAX,16:15,16:06,88.0,79.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444109,WN,12/31/2023,2218.0,N492WN,LAS,10:15,10:30,90.0,80.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444124,WN,12/31/2024,1073.0,N7722B,DEN,07:55,07:58,145.0,127.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444129,WN,12/31/2024,2290.0,N230WN,DEN,13:20,14:02,150.0,129.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444133,WN,12/31/2024,2712.0,N8627B,DEN,09:55,09:52,140.0,124.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
444159,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

### Standardize columns and drop missing tail number rows

In [8]:
#Standardizing column names 
departures_faa_df.columns = (
    departures_faa_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[\s\(\)/\-]+', '_', regex=True)
    .str.replace(r'[^\w]', '', regex=True)
    .str.strip('_')
)

# Drop flights without FAA aircraft information
departures_faa_cleaned = departures_faa_df.dropna(subset=["n_number"]).copy()

print(f"departures_faa_df shape: {departures_faa_cleaned.shape}")
print(f"Data types:\n{departures_faa_cleaned.dtypes}")
display(departures_faa_cleaned.head())

departures_faa_df shape: (423890, 54)
Data types:
carrier_code                                   str
date_mm_dd_yyyy                                str
flight_number                              float64
tail_number                                    str
destination_airport                            str
scheduled_departure_time                       str
actual_departure_time                          str
scheduled_elapsed_time_minutes             float64
actual_elapsed_time_minutes                float64
departure_delay_minutes                    float64
wheels_off_time                                str
taxi_out_time_minutes                      float64
delay_carrier_minutes                      float64
delay_weather_minutes                      float64
delay_national_aviation_system_minutes     float64
delay_security_minutes                     float64
delay_late_aircraft_arrival_minutes        float64
is_cancelled                                 int64
outcome                                    float64
departure_delay_min                        float64
scheduled_dep_dt                               str
actual_dep_dt                                  str
date                                           str
6hr_cutoff_dt                                  str
year                                       float64
month                                      float64
month_name                                     str
day_of_week                                float64
is_weekend                                   int64
sched_dep_hour                             float64
dep_time_of_day                                str
is_holiday                                   int64
days_until_holiday                         float64
days_from_holiday                          float64
mod_tail_number                                str
tail_key                                    string
n_number                                       str
year_mfr                                       str
type_aircraft                                  str
type_engine                                float64
mfr_mdl_code                                   str
eng_mfr_mdl                                float64
code                                           str
mfr                                            str
model                                          str
no_eng                                     float64
no_seats                                   float64
ac_weight                                      str
speed                                      float64
code_eng                                   float64
mfr_eng                                        str
model_eng                                      str
thrust                                     float64
merge                                     category
dtype: object

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,model,no_eng,no_seats,ac_weight,speed,code_eng,mfr_eng,model_eng,thrust,merge
0,AA,01/01/2022,16.0,N110AN,JFK,11:46,11:35,343.0,328.0,-11.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
1,AA,01/01/2022,234.0,N112AN,JFK,07:00,06:54,329.0,328.0,-6.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
2,AA,01/01/2022,276.0,N109NN,JFK,22:59,22:51,333.0,329.0,-8.0,...,A321-231,2.0,379.0,CLASS 3,0.0,34611.0,IAE,V2533-A5,31600.0,both
3,AA,01/01/2022,369.0,N341SV,MIA,07:47,07:43,330.0,303.0,-4.0,...,737-8,2.0,175.0,CLASS 3,0.0,13134.0,CFM INTL,LEAP-1B25,26786.0,both
4,AA,01/01/2022,1175.0,N992AN,DFW,17:21,17:31,208.0,195.0,10.0,...,737-823,2.0,162.0,CLASS 3,0.0,13074.0,CFM INTL,CFM56-7B24/3,22800.0,both

### Merge Departures/FAA and NOAA Data using time horizons
Using the time horizons (1, 2, 4, 6, 12) hours before departure, we will end up with five merged datasets. For simplicity, we will start by merging weather data 1 hour before departure and write a function to create the other datasets.

In [9]:
# Only use weather feature columns
weather_features = [
    "visibility",
    "ceiling_height",
    "wind_speed",
    "wind_direction",
    "precipitation",
    "temperature",
    "dew_point_temperature",
    "relative_humidity",
    "altimeter",
    "sky_cover_summation_baseht_1"
]

noaa_df = (
    noaa_df[["DATE"] + weather_features]
    .rename(columns={"DATE": "weather_source_dt"})
)

In [10]:
departures_faa_cleaned["scheduled_dep_dt"] = pd.to_datetime(
    departures_faa_cleaned["scheduled_dep_dt"], errors="coerce"
)
departures_faa_cleaned["weather_cutoff_dt"] = (
    departures_faa_cleaned["scheduled_dep_dt"] - pd.Timedelta(hours=1)
)

noaa_df["weather_observation_dt"] = pd.to_datetime(
    noaa_df["weather_source_dt"], errors="coerce"
)

departures_faa_noaa_df = pd.merge_asof(
    departures_faa_cleaned.dropna(subset=["weather_cutoff_dt"]).sort_values("weather_cutoff_dt"),
    noaa_df.dropna(subset=["weather_observation_dt"]).sort_values("weather_observation_dt"),
    left_on="weather_cutoff_dt",
    right_on="weather_observation_dt",
    direction="backward",
    tolerance=pd.Timedelta(minutes=60),
    suffixes=("", "_weather"),
)

print(f"Merged shape: {departures_faa_noaa_df.shape}")
print(f"Weather match rate: {departures_faa_noaa_df['weather_observation_dt'].notna().mean():.2%}")
display(departures_faa_noaa_df.head())

Merged shape: (423890, 67)
Weather match rate: 99.56%

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,ceiling_height,wind_speed,wind_direction,precipitation,temperature,dew_point_temperature,relative_humidity,altimeter,sky_cover_summation_baseht_1,weather_observation_dt
0,AA,01/01/2022,2614.0,N949NN,ORD,05:15,00:00,260.0,0.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
1,WN,01/01/2022,2271.0,N7723E,DEN,05:25,05:25,145.0,147.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
2,DL,01/01/2022,1211.0,N124DU,SLC,05:55,05:52,118.0,103.0,-3.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
3,DL,01/01/2022,768.0,N584NW,ATL,06:00,06:14,272.0,276.0,14.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00
4,UA,01/01/2022,2604.0,N77536,LAX,06:02,05:56,98.0,81.0,-6.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00

### Identify Mismatches

In [11]:
weather_matched = departures_faa_noaa_df["weather_observation_dt"].notna()

print(weather_matched.value_counts().rename({True: "matched", False: "unmatched"}))
print(f"Weather match rate: {weather_matched.mean():.2%}")

weather_mismatches_df = departures_faa_noaa_df[~weather_matched]
display(weather_mismatches_df)

weather_observation_dt
matched      422043
unmatched      1847
Name: count, dtype: int64
Weather match rate: 99.56%

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,ceiling_height,wind_speed,wind_direction,precipitation,temperature,dew_point_temperature,relative_humidity,altimeter,sky_cover_summation_baseht_1,weather_observation_dt
24609,WN,05/05/2022,2318.0,N941WN,SAN,18:05,18:02,95.0,83.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
24610,UA,05/05/2022,2356.0,N78448,AUS,18:33,20:07,206.0,193.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
24611,F9,05/05/2022,2070.0,N708FR,LAS,18:36,18:32,97.0,100.0,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
24612,UA,05/05/2022,1299.0,N75853,DEN,18:41,18:40,151.0,143.0,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
24613,UA,05/05/2022,2385.0,N428UA,SNA,18:45,18:44,90.0,83.0,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414889,AA,04/03/2026,166.0,N107NN,JFK,12:39,12:33,336.0,383.0,-6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
414890,UA,04/03/2026,488.0,N27283,RDU,12:40,12:39,322.0,324.0,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
414891,UA,04/03/2026,1705.0,N17300,PIT,12:45,12:38,306.0,293.0,-7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
414892,UA,04/03/2026,2121.0,N75429,DEN,12:45,12:49,164.0,155.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
414893,AA,04/03/2026,2114.0,N310RF,PHX,12:46,12:43,123.0,122.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

### Standardize columns and drop missing weather_observation_dt

In [12]:
#Standardizing column names 
departures_faa_noaa_df.columns = (
    departures_faa_noaa_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[\s\(\)/\-]+', '_', regex=True)
    .str.replace(r'[^\w]', '', regex=True)
    .str.strip('_')
)

# Drop flights without weather information
departures_faa_noaa_cleaned = departures_faa_noaa_df.dropna(subset=["weather_observation_dt"]).copy()

print(f"departures_faa_noaa_cleaned shape: {departures_faa_noaa_cleaned.shape}")
print(f"Data types:\n{departures_faa_noaa_cleaned.dtypes}")
display(departures_faa_noaa_cleaned.head())

departures_faa_noaa_cleaned shape: (422043, 67)
Data types:
carrier_code                               str
date_mm_dd_yyyy                            str
flight_number                          float64
tail_number                                str
destination_airport                        str
                                     ...
dew_point_temperature                  float64
relative_humidity                      float64
altimeter                              float64
sky_cover_summation_baseht_1           float64
weather_observation_dt          datetime64[us]
Length: 67, dtype: object

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,ceiling_height,wind_speed,wind_direction,precipitation,temperature,dew_point_temperature,relative_humidity,altimeter,sky_cover_summation_baseht_1,weather_observation_dt
0,AA,01/01/2022,2614.0,N949NN,ORD,05:15,00:00,260.0,0.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
1,WN,01/01/2022,2271.0,N7723E,DEN,05:25,05:25,145.0,147.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
2,DL,01/01/2022,1211.0,N124DU,SLC,05:55,05:52,118.0,103.0,-3.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
3,DL,01/01/2022,768.0,N584NW,ATL,06:00,06:14,272.0,276.0,14.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00
4,UA,01/01/2022,2604.0,N77536,LAX,06:02,05:56,98.0,81.0,-6.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00

### Feature decisions before missing-value handling

The table below separates model inputs from targets and merge/split metadata. Feature missingness should be handled after the chronological split so that imputation statistics are learned from the training set only.

In [13]:
summary = pd.DataFrame({
    "column_name": departures_faa_noaa_cleaned.columns,
    "dtype": departures_faa_noaa_cleaned.dtypes.values,
    "nulls_count": departures_faa_noaa_cleaned.isna().sum().values,
    "nulls_percent": (departures_faa_noaa_cleaned.isna().mean().values * 100).round(3),
    "unique_values": departures_faa_noaa_cleaned.nunique().values
})

display(summary)

,column_name,dtype,nulls_count,nulls_percent,unique_values
0,carrier_code,str,0,0.000,8
1,date_mm_dd_yyyy,str,0,0.000,1579
2,flight_number,float64,0,0.000,3047
3,tail_number,str,0,0.000,4313
4,destination_airport,str,0,0.000,72
...,...,...,...,...,...
62,dew_point_temperature,float64,10,0.002,60
63,relative_humidity,float64,10,0.002,81
64,altimeter,float64,0,0.000,127
65,sky_cover_summation_baseht_1,float64,63514,15.049,75
66,weather_observation_dt,datetime64[us],0,0.000,31852

In [14]:
departures_copy = departures_faa_noaa_cleaned.copy()
display(departures_copy)

,carrier_code,date_mm_dd_yyyy,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time_minutes,actual_elapsed_time_minutes,departure_delay_minutes,...,ceiling_height,wind_speed,wind_direction,precipitation,temperature,dew_point_temperature,relative_humidity,altimeter,sky_cover_summation_baseht_1,weather_observation_dt
0,AA,01/01/2022,2614.0,N949NN,ORD,05:15,00:00,260.0,0.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
1,WN,01/01/2022,2271.0,N7723E,DEN,05:25,05:25,145.0,147.0,0.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
2,DL,01/01/2022,1211.0,N124DU,SLC,05:55,05:52,118.0,103.0,-3.0,...,22000.0,5.1,310.0,0.0,9.4,5.0,74.0,1014.6,914.0,2022-01-01 03:56:00
3,DL,01/01/2022,768.0,N584NW,ATL,06:00,06:14,272.0,276.0,14.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00
4,UA,01/01/2022,2604.0,N77536,LAX,06:02,05:56,98.0,81.0,-6.0,...,22000.0,2.6,330.0,0.0,8.9,5.0,77.0,1015.6,NaN,2022-01-01 04:56:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423885,UA,04/30/2026,1815.0,N47293,BNA,23:59,23:59,271.0,257.0,0.0,...,NaN,9.8,290.0,NaN,17.2,10.6,65.0,1013.9,305.0,2026-04-30 22:56:00
423886,DL,04/30/2026,2789.0,N834DN,MSP,23:59,00:27,227.0,219.0,28.0,...,NaN,9.8,290.0,NaN,17.2,10.6,65.0,1013.9,305.0,2026-04-30 22:56:00
423887,AA,04/30/2026,1430.0,N544UW,DFW,23:59,00:03,214.0,202.0,4.0,...,NaN,9.8,290.0,NaN,17.2,10.6,65.0,1013.9,305.0,2026-04-30 22:56:00
423888,UA,04/30/2026,1807.0,N27520,AUS,23:59,23:58,214.0,216.0,-1.0,...,NaN,9.8,290.0,NaN,17.2,10.6,65.0,1013.9,305.0,2026-04-30 22:56:00
423889,UA,04/30/2026,1112.0,N77543,MCO,23:59,23:57,328.0,315.0,-2.0,...,NaN,9.8,290.0,NaN,17.2,10.6,65.0,1013.9,305.0,2026-04-30 22:56:00

In [ ]:
departures_features = [
    'carrier_code', 
    'destination_airport', 
    'scheduled_elapsed_time_minutes', 
    'year', 
    'month', 
    'day_of_week', 
    'is_weekend',
    'sched_dep_hour',
    'outcome',
    'days_until_holiday',
    'days_from_holiday'
]

faa_features = [
    'year_mfr', 
    'model', 
    'no_seats'
]

weather_features = [
    'visibility', 
    'ceiling_height', 
    'wind_speed', 
    'wind_direction', 
    'temperature', 
    'dew_point_temperature', 
    'relative_humidity', 
    'altimeter'
]

# Keep scheduled_dep_dt as chronological split/prediction-horizon metadata.
# It should not be passed to the model as a raw feature.
departures_faa_noaa_cleaned = departures_faa_noaa_cleaned[
    ["date", "scheduled_dep_dt", "actual_dep_dt"]
    + departures_features
    + faa_features
    + weather_features
    + ["departure_delay_minutes"]
]

In [16]:
summary = pd.DataFrame({
    "column_name": departures_faa_noaa_cleaned.columns,
    "dtype": departures_faa_noaa_cleaned.dtypes.values,
    "nulls_count": departures_faa_noaa_cleaned.isna().sum().values,
    "nulls_percent": (departures_faa_noaa_cleaned.isna().mean().values * 100).round(3),
    "unique_values": departures_faa_noaa_cleaned.nunique().values
})

display(summary)

,column_name,dtype,nulls_count,nulls_percent,unique_values
0,date,str,0,0.000,1579
1,scheduled_dep_dt,datetime64[us],0,0.000,286406
2,actual_dep_dt,str,126,0.030,366594
3,carrier_code,str,0,0.000,8
4,destination_airport,str,0,0.000,72
5,scheduled_elapsed_time_minutes,float64,0,0.000,303
6,year,float64,0,0.000,5
7,month,float64,0,0.000,12
8,day_of_week,float64,0,0.000,7
9,is_weekend,int64,0,0.000,2
10,sched_dep_hour,float64,0,0.000,21
11,outcome,float64,0,0.000,9
12,year_mfr,str,0,0.000,44
13,model,str,0,0.000,109
14,no_seats,float64,0,0.000,44
15,visibility,float64,0,0.000,26
16,ceiling_height,float64,28705,6.801,77
17,wind_speed,float64,31,0.007,40
18,wind_direction,float64,47917,11.354,37
19,temperature,float64,10,0.002,67
20,dew_point_temperature,float64,10,0.002,60
21,relative_humidity,float64,10,0.002,81
22,altimeter,float64,0,0.000,127
23,departure_delay_minutes,float64,0,0.000,976

### Drop NAs

In [17]:
departures_faa_noaa_cleaned = departures_faa_noaa_cleaned.dropna()
print(f"departures_faa_noaa_cleaned shape: {departures_faa_noaa_cleaned.shape}")
display(departures_faa_noaa_cleaned.head())

departures_faa_noaa_cleaned shape: (349555, 24)

,date,scheduled_dep_dt,actual_dep_dt,carrier_code,destination_airport,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,...,no_seats,visibility,ceiling_height,wind_speed,wind_direction,temperature,dew_point_temperature,relative_humidity,altimeter,departure_delay_minutes
0,2022-01-01,2022-01-01 05:15:00,2022-01-01 00:00:00,AA,ORD,260.0,2022.0,1.0,5.0,1,...,162.0,16.093,22000.0,5.1,310.0,9.4,5.0,74.0,1014.6,0.0
1,2022-01-01,2022-01-01 05:25:00,2022-01-01 05:25:00,WN,DEN,145.0,2022.0,1.0,5.0,1,...,149.0,16.093,22000.0,5.1,310.0,9.4,5.0,74.0,1014.6,0.0
2,2022-01-01,2022-01-01 05:55:00,2022-01-01 05:52:00,DL,SLC,118.0,2022.0,1.0,5.0,1,...,133.0,16.093,22000.0,5.1,310.0,9.4,5.0,74.0,1014.6,-3.0
3,2022-01-01,2022-01-01 06:00:00,2022-01-01 06:14:00,DL,ATL,272.0,2022.0,1.0,5.0,1,...,275.0,16.093,22000.0,2.6,330.0,8.9,5.0,77.0,1015.6,14.0
4,2022-01-01,2022-01-01 06:02:00,2022-01-01 05:56:00,UA,LAX,98.0,2022.0,1.0,5.0,1,...,149.0,16.093,22000.0,2.6,330.0,8.9,5.0,77.0,1015.6,-6.0

### Additional engineered fields

**Aircraft and calendar**

- `aircraft_age`: flight year minus aircraft manufacture year
- `week_num`: 1-based seven-day period beginning January 1

**Cyclical time**

- `sched_dep_hour_sin`, `sched_dep_hour_cos`: circular representation of scheduled departure hour (PENDING)
- `month_sin`, `month_cos`: circular representation of month (PENDING)

**Weather**

- `wind_direction_sin`, `wind_direction_cos`: circular representation of wind direction (PENDING)
- `temperature_dewpoint_spread`: temperature minus dew point

**Recent airport conditions**

- `airport_delay_average_1h`: average delay observed in the hour before the prediction cutoff
- `airport_delay_stddev_1h`: sample delay stddev over that window
- `airport_departures_observed_1h`: number of observed departures supporting those statistics

The prediction cutoff is one hour before scheduled departure. Only flights that had departed by the cutoff are used, and the current flight is excluded to prevent data leakage.

#### Aircraft and calendar fields

In [18]:
import numpy as np
from pandas.tseries.holiday import USFederalHolidayCalendar

departures_faa_noaa_cleaned = departures_faa_noaa_cleaned.copy()
departures_faa_noaa_cleaned["date"] = pd.to_datetime(departures_faa_noaa_cleaned["date"], errors="coerce")
departures_faa_noaa_cleaned["scheduled_dep_dt"] = pd.to_datetime(departures_faa_noaa_cleaned["scheduled_dep_dt"], errors="coerce")
departures_faa_noaa_cleaned["year_mfr"] = pd.to_numeric(departures_faa_noaa_cleaned["year_mfr"], errors="coerce")

# Aircraft age
departures_faa_noaa_cleaned["aircraft_age"] = departures_faa_noaa_cleaned["year"] - departures_faa_noaa_cleaned["year_mfr"]
departures_faa_noaa_cleaned.loc[departures_faa_noaa_cleaned["aircraft_age"] < 0, "aircraft_age"] = np.nan

# Seven-day periods relative to January 1
departures_faa_noaa_cleaned["week_num"] = ((departures_faa_noaa_cleaned["date"].dt.dayofyear - 1) // 7 + 1).astype("int8")

#### Cyclical time fields

Sine and cosine place periodic values on a circle, since hour 23 is close to hour 0 and December is close to January.

In [ ]:
# hour_angle = 2 * np.pi * departures_faa_noaa_cleaned["sched_dep_hour"] / 24
# month_angle = 2 * np.pi * (departures_faa_noaa_cleaned["month"] - 1) / 12

# departures_faa_noaa_cleaned["sched_dep_hour_sin"] = np.sin(hour_angle)
# departures_faa_noaa_cleaned["sched_dep_hour_cos"] = np.cos(hour_angle)
# departures_faa_noaa_cleaned["month_sin"] = np.sin(month_angle)
# departures_faa_noaa_cleaned["month_cos"] = np.cos(month_angle)

#### Weather-derived fields

In [ ]:
# wind_angle = np.deg2rad(departures_faa_noaa_cleaned["wind_direction"] % 360)
# departures_faa_noaa_cleaned["wind_direction_sin"] = np.sin(wind_angle)
# departures_faa_noaa_cleaned["wind_direction_cos"] = np.cos(wind_angle)

# A small spread indicates air close to saturation and possible fog.
departures_faa_noaa_cleaned["temperature_dewpoint_spread"] = (departures_faa_noaa_cleaned["temperature"] - departures_faa_noaa_cleaned["dew_point_temperature"])

#### Recent airport delay fields

To derive the recent airport conditions, we define a lookback window of 1 hour. Only using delays from flights whos delays are already observable in the lookback window.

e.g. 
scheduled_departure = 3:00 PM
prediction time     = 2:00 PM (time horizon of 1h)
lookback window     = 1:00 PM to 2:00 PM

In [21]:
HORIZON_HOURS = 1
LOOKBACK_HOURS = 1

airport_events = departures_df[["actual_dep_dt", "departure_delay_minutes"]].copy()
airport_events["actual_dep_dt"] = pd.to_datetime(airport_events["actual_dep_dt"], errors="coerce")
airport_events["departure_delay_minutes"] = pd.to_numeric(airport_events["departure_delay_minutes"], errors="coerce")
airport_events = airport_events.dropna(subset=["actual_dep_dt", "departure_delay_minutes"]).sort_values("actual_dep_dt")

### Flight lookback helper function

In [ ]:
def get_recent_airport_delay_stats(row):
    scheduled_departure = row["scheduled_dep_dt"]

    prediction_cutoff = scheduled_departure - pd.Timedelta(hours=HORIZON_HOURS)
    window_start = prediction_cutoff - pd.Timedelta(hours=LOOKBACK_HOURS)

    recent_departures = airport_events[
        (airport_events["actual_dep_dt"] >= window_start)
        & (airport_events["actual_dep_dt"] <= prediction_cutoff)
    ]

    return pd.Series({
        "airport_delay_average_1h": recent_departures["departure_delay_minutes"].mean(),
        "airport_delay_stddev_1h": recent_departures["departure_delay_minutes"].std(),
        "airport_departures_observed_1h": len(recent_departures)
    })

In [23]:
departures_faa_noaa_cleaned["scheduled_dep_dt"] = pd.to_datetime(departures_faa_noaa_cleaned["scheduled_dep_dt"], errors="coerce")

recent_delay_features = departures_faa_noaa_cleaned.apply(get_recent_airport_delay_stats, axis=1)

df = pd.concat([departures_faa_noaa_cleaned, recent_delay_features], axis=1)

### Final combined dataset

In [ ]:
engineered_features = [
    "aircraft_age",
    "week_num",
    # "sched_dep_hour_sin",
    # "sched_dep_hour_cos",
    # "month_sin",
    # "month_cos",
    # "wind_direction_sin",
    # "wind_direction_cos",
    "temperature_dewpoint_spread",
    "airport_delay_average_1h",
    "airport_delay_stddev_1h",
    "airport_departures_observed_1h",
]

# Sort chronologically and keep the regression target as the final column.
target_column = "departure_delay_minutes"
departures_faa_noaa_cleaned = df.sort_values("scheduled_dep_dt").reset_index(drop=True)
departures_faa_noaa_cleaned = departures_faa_noaa_cleaned[[column for column in departures_faa_noaa_cleaned.columns if column != target_column] + [target_column]]

In [25]:
print(f"Final combined shape: {departures_faa_noaa_cleaned.shape}")
display(departures_faa_noaa_cleaned.head())

missing_summary = pd.DataFrame({
    "column_name": departures_faa_noaa_cleaned.columns,
    "dtype": departures_faa_noaa_cleaned.dtypes.astype(str).values,
    "missing_count": departures_faa_noaa_cleaned.isna().sum().values,
    "missing_percent": (departures_faa_noaa_cleaned.isna().mean().values * 100).round(3),
}).reset_index(drop=True)

display(missing_summary)

Final combined shape: (349555, 36)

,date,scheduled_dep_dt,actual_dep_dt,carrier_code,destination_airport,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,...,sched_dep_hour_cos,month_sin,month_cos,wind_direction_sin,wind_direction_cos,temperature_dewpoint_spread,airport_delay_average_1h,airport_delay_variance_1h,airport_departures_observed_1h,departure_delay_minutes
0,2022-01-01,2022-01-01 05:15:00,2022-01-01 00:00:00,AA,ORD,260.0,2022.0,1.0,5.0,1,...,2.588190e-01,0.0,1.0,-0.766044,0.642788,4.4,NaN,NaN,0.0,0.0
1,2022-01-01,2022-01-01 05:25:00,2022-01-01 05:25:00,WN,DEN,145.0,2022.0,1.0,5.0,1,...,2.588190e-01,0.0,1.0,-0.766044,0.642788,4.4,NaN,NaN,0.0,0.0
2,2022-01-01,2022-01-01 05:55:00,2022-01-01 05:52:00,DL,SLC,118.0,2022.0,1.0,5.0,1,...,2.588190e-01,0.0,1.0,-0.766044,0.642788,4.4,NaN,NaN,0.0,-3.0
3,2022-01-01,2022-01-01 06:00:00,2022-01-01 06:14:00,DL,ATL,272.0,2022.0,1.0,5.0,1,...,6.123234e-17,0.0,1.0,-0.500000,0.866025,3.9,NaN,NaN,0.0,14.0
4,2022-01-01,2022-01-01 06:02:00,2022-01-01 05:56:00,UA,LAX,98.0,2022.0,1.0,5.0,1,...,6.123234e-17,0.0,1.0,-0.500000,0.866025,3.9,NaN,NaN,0.0,-6.0

,column_name,dtype,missing_count,missing_percent
0,date,datetime64[us],0,0.000
1,scheduled_dep_dt,datetime64[us],0,0.000
2,actual_dep_dt,str,0,0.000
3,carrier_code,str,0,0.000
4,destination_airport,str,0,0.000
5,scheduled_elapsed_time_minutes,float64,0,0.000
6,year,float64,0,0.000
7,month,float64,0,0.000
8,day_of_week,float64,0,0.000
9,is_weekend,int64,0,0.000
10,sched_dep_hour,float64,0,0.000
11,outcome,float64,0,0.000
12,year_mfr,float64,6589,1.885
13,model,str,0,0.000
14,no_seats,float64,0,0.000
15,visibility,float64,0,0.000
16,ceiling_height,float64,0,0.000
17,wind_speed,float64,0,0.000
18,wind_direction,float64,0,0.000
19,temperature,float64,0,0.000
20,dew_point_temperature,float64,0,0.000
21,relative_humidity,float64,0,0.000
22,altimeter,float64,0,0.000
23,aircraft_age,float64,6589,1.885
24,week_num,int8,0,0.000
25,sched_dep_hour_sin,float64,0,0.000
26,sched_dep_hour_cos,float64,0,0.000
27,month_sin,float64,0,0.000
28,month_cos,float64,0,0.000
29,wind_direction_sin,float64,0,0.000
30,wind_direction_cos,float64,0,0.000
31,temperature_dewpoint_spread,float64,0,0.000
32,airport_delay_average_1h,float64,11382,3.256
33,airport_delay_variance_1h,float64,16475,4.713
34,airport_departures_observed_1h,float64,0,0.000
35,departure_delay_minutes,float64,0,0.000

In [31]:
rows_before_cleanup = len(departures_faa_noaa_cleaned)

departures_faa_noaa_cleaned = departures_faa_noaa_cleaned.dropna(subset=["aircraft_age"])

scheduled_departure = pd.to_datetime(departures_faa_noaa_cleaned["scheduled_dep_dt"], errors="coerce")
actual_departure = pd.to_datetime(departures_faa_noaa_cleaned["actual_dep_dt"], errors="coerce")
reported_delay = pd.to_numeric(departures_faa_noaa_cleaned["departure_delay_minutes"], errors="coerce")
timestamp_delay = (actual_departure - scheduled_departure).dt.total_seconds().div(60)
delay_matches = (
    timestamp_delay.notna()
    & reported_delay.notna()
    & np.isclose(timestamp_delay, reported_delay, atol=0.5)
)

mismatching_delay_rows = int((~delay_matches).sum())
departures_faa_noaa_cleaned = departures_faa_noaa_cleaned.loc[delay_matches].reset_index(drop=True)

print(f"Rows before cleanup: {rows_before_cleanup:,}")
print(f"Rows removed for timestamp/delay mismatch: {mismatching_delay_rows:,}")
print(f"Cleaned shape: {departures_faa_noaa_cleaned.shape}")
display(departures_faa_noaa_cleaned.head())

Rows before cleanup: 334,086
Rows removed for timestamp/delay mismatch: 0
Cleaned shape: (334086, 38)

,date,scheduled_dep_dt,actual_dep_dt,carrier_code,destination_airport,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,...,month_cos,wind_direction_sin,wind_direction_cos,temperature_dewpoint_spread,airport_delay_average_1h,airport_delay_variance_1h,airport_departures_observed_1h,has_delay_average_history,has_delay_variance_history,departure_delay_minutes
0,2022-01-01,2022-01-01 05:25:00,2022-01-01 05:25:00,WN,DEN,145.0,2022.0,1.0,5.0,1,...,1.0,-0.766044,0.642788,4.4,0.0,0.0,0.0,0,0,0.0
1,2022-01-01,2022-01-01 05:55:00,2022-01-01 05:52:00,DL,SLC,118.0,2022.0,1.0,5.0,1,...,1.0,-0.766044,0.642788,4.4,0.0,0.0,0.0,0,0,-3.0
2,2022-01-01,2022-01-01 06:00:00,2022-01-01 06:14:00,DL,ATL,272.0,2022.0,1.0,5.0,1,...,1.0,-0.500000,0.866025,3.9,0.0,0.0,0.0,0,0,14.0
3,2022-01-01,2022-01-01 06:02:00,2022-01-01 05:56:00,UA,LAX,98.0,2022.0,1.0,5.0,1,...,1.0,-0.500000,0.866025,3.9,0.0,0.0,0.0,0,0,-6.0
4,2022-01-01,2022-01-01 06:10:00,2022-01-01 07:51:00,DL,MSP,218.0,2022.0,1.0,5.0,1,...,1.0,-0.500000,0.866025,3.9,0.0,0.0,0.0,0,0,101.0

#### Airport delay average and stddev

- `airport_delay_average_1h` is null when **no qualifying departures** occurred during the one-hour lookback window. With zero delay values, there is no average to calculate.
- `airport_delay_stddev_1h` is null when the window contains **fewer than two qualifying departures**. Pandas calculates sample stddev with `ddof=1`, which requires at least two values.

Hence, we will fillna(0)

In [ ]:
departures_faa_noaa_cleaned["airport_delay_average_1h"] = (departures_faa_noaa_cleaned["airport_delay_average_1h"].fillna(0.0))
departures_faa_noaa_cleaned["airport_delay_stddev_1h"] = (departures_faa_noaa_cleaned["airport_delay_stddev_1h"].fillna(0.0))

# Keep the target as the final column after adding the two history flags.
target_column = "departure_delay_minutes"
departures_faa_noaa_cleaned = departures_faa_noaa_cleaned[[
    column for column in departures_faa_noaa_cleaned.columns
    if column != target_column
] + [target_column]]

In [33]:
missing_summary = pd.DataFrame({
    "column_name": departures_faa_noaa_cleaned.columns,
    "dtype": departures_faa_noaa_cleaned.dtypes.astype(str).values,
    "missing_count": departures_faa_noaa_cleaned.isna().sum().values,
    "missing_percent": (departures_faa_noaa_cleaned.isna().mean().values * 100).round(3),
}).reset_index(drop=True)

display(missing_summary)

,column_name,dtype,missing_count,missing_percent
0,date,datetime64[us],0,0.0
1,scheduled_dep_dt,datetime64[us],0,0.0
2,actual_dep_dt,str,0,0.0
3,carrier_code,str,0,0.0
4,destination_airport,str,0,0.0
5,scheduled_elapsed_time_minutes,float64,0,0.0
6,year,float64,0,0.0
7,month,float64,0,0.0
8,day_of_week,float64,0,0.0
9,is_weekend,int64,0,0.0
10,sched_dep_hour,float64,0,0.0
11,outcome,float64,0,0.0
12,year_mfr,float64,0,0.0
13,model,str,0,0.0
14,no_seats,float64,0,0.0
15,visibility,float64,0,0.0
16,ceiling_height,float64,0,0.0
17,wind_speed,float64,0,0.0
18,wind_direction,float64,0,0.0
19,temperature,float64,0,0.0
20,dew_point_temperature,float64,0,0.0
21,relative_humidity,float64,0,0.0
22,altimeter,float64,0,0.0
23,aircraft_age,float64,0,0.0
24,week_num,int8,0,0.0
25,sched_dep_hour_sin,float64,0,0.0
26,sched_dep_hour_cos,float64,0,0.0
27,month_sin,float64,0,0.0
28,month_cos,float64,0,0.0
29,wind_direction_sin,float64,0,0.0
30,wind_direction_cos,float64,0,0.0
31,temperature_dewpoint_spread,float64,0,0.0
32,airport_delay_average_1h,float64,0,0.0
33,airport_delay_variance_1h,float64,0,0.0
34,airport_departures_observed_1h,float64,0,0.0
35,has_delay_average_history,int64,0,0.0
36,has_delay_variance_history,int64,0,0.0
37,departure_delay_minutes,float64,0,0.0