In [1]:
#Load Libraries
import os
from pathlib import Path
import pandas as pd
import gdown

In [2]:
def load_sfo_noaa_data():
    # Google Drive folder with SFO NOAA PSV files
    url = "https://drive.google.com/drive/folders/1qZHc7AxcL_1GaD2ZTN2n8O7lP7VmoLoh"
    folder = "data"
    output = "NOAA_SFO_2022_2026.parquet"
    
    # Download only if the folder doesn't exist
    if not os.path.exists(folder):
        gdown.download_folder(url, output=folder, quiet=False, use_cookies=False)
    
    # Load all .psv files
    psv_files = list(Path(folder).rglob("*.psv"))
    
    dfs = []
    for file in psv_files:
        df = pd.read_csv(file, sep="|", dtype=str, low_memory=False)
        dfs.append(df)
    
    # Combine and export
    noaa_sfo_df = pd.concat(dfs, ignore_index=True)
    noaa_sfo_df.to_parquet(output, index=False)
    
    return noaa_sfo_df

NOAA_SFO_df = load_sfo_noaa_data()

In [3]:
# Analyze data downloaded
print("NOAA SFO 2022-2026:")
print(f"\nShape: {NOAA_SFO_df.shape}")

print("\nColumns and Datatypes:")
display(NOAA_SFO_df.dtypes)

print("\nData Preview:")
display(NOAA_SFO_df.head())

NOAA SFO 2022-2026:

Shape: (89176, 329)

Columns and Datatypes:

STATION                  str
Station_name             str
DATE                     str
Year                     str
Month                    str
                        ...
REM_Measurement_Code     str
REM_Quality_Code         str
REM_Report_Type          str
REM_Source_Code          str
REM_Source_Station_ID    str
Length: 329, dtype: object

Data Preview:

,STATION,Station_name,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,...,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,REM,REM_Measurement_Code,REM_Quality_Code,REM_Report_Type,REM_Source_Code,REM_Source_Station_ID
0,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:00:00,2024,01,01,00,00,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN08072494 32666 80204 10133 20100 30154 4018...,NaN,NaN,FM12,223,ICAO-KSFO
1,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:56:00,2024,01,01,00,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010056Z 01004KT 10SM FEW040 B...,NaN,NaN,FM15,223,ICAO-KSFO
2,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T01:56:00,2024,01,01,01,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010156Z 00000KT 10SM FEW040 B...,NaN,NaN,FM15,223,ICAO-KSFO
3,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T02:56:00,2024,01,01,02,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET096METAR KSFO 010256Z 00000KT 10SM FEW020 S...,NaN,NaN,FM15,223,ICAO-KSFO
4,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T03:00:00,2024,01,01,03,00,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN06472494 32566 60000 10128 20094 30158 4018...,NaN,NaN,FM12,223,ICAO-KSFO

In [4]:
NOAA_SFO_df

,STATION,Station_name,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,...,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,REM,REM_Measurement_Code,REM_Quality_Code,REM_Report_Type,REM_Source_Code,REM_Source_Station_ID
0,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:00:00,2024,01,01,00,00,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN08072494 32666 80204 10133 20100 30154 4018...,NaN,NaN,FM12,223,ICAO-KSFO
1,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:56:00,2024,01,01,00,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010056Z 01004KT 10SM FEW040 B...,NaN,NaN,FM15,223,ICAO-KSFO
2,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T01:56:00,2024,01,01,01,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010156Z 00000KT 10SM FEW040 B...,NaN,NaN,FM15,223,ICAO-KSFO
3,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T02:56:00,2024,01,01,02,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET096METAR KSFO 010256Z 00000KT 10SM FEW020 S...,NaN,NaN,FM15,223,ICAO-KSFO
4,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T03:00:00,2024,01,01,03,00,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN06472494 32566 60000 10128 20094 30158 4018...,NaN,NaN,FM12,223,ICAO-KSFO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89171,USW00023234,SAN FRANCISCO INTL AP,2025-12-31T21:00:00,2025,12,31,21,00,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN07672494 11866 81205 10111 20067 30121 4015...,NaN,NaN,FM12,223,ICAO-KSFO
89172,USW00023234,SAN FRANCISCO INTL AP,2025-12-31T21:56:00,2025,12,31,21,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET093METAR KSFO 312156Z 13003KT 10SM -RA FEW0...,NaN,NaN,FM15,223,ICAO-KSFO
89173,USW00023234,SAN FRANCISCO INTL AP,2025-12-31T22:56:00,2025,12,31,22,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET092METAR KSFO 312256Z 13004KT 10SM RA FEW03...,NaN,NaN,FM15,223,ICAO-KSFO
89174,USW00023234,SAN FRANCISCO INTL AP,2025-12-31T23:11:00,2025,12,31,23,11,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET095SPECI KSFO 312311Z 17004KT 5SM -RA BR SC...,NaN,NaN,FM16,223,ICAO-KSFO
89175,USW00023234,SAN FRANCISCO INTL AP,2025-12-31T23:56:00,2025,12,31,23,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET125METAR KSFO 312356Z 11003KT 5SM RA BR FEW...,NaN,NaN,FM15,223,ICAO-KSFO